config/routes.rb
Rails.application.routes.draw do
	root "creatures#index" #localhost:3000

	get "/creatures", to: "creatures#index", as: "creatures"
	get "/creatures/new", to: "creatures#new", as: "new_creature"
	post "/creatures" => "creatures#create"
	get "/creatures/:id", to: "creatures#show", as: "creature"
	get "/creatures/:id/edit", to: "creatures#edit", as: "edit_creature"
	patch "/creatures/:id", to: "creatures#update"
	delete "/creatures/:id", to: "creatures#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
	def index 
		@creatures = Creature.all
	end

	def new
		@creature = Creature.new
	end 

	def create
		creature_params = params.require(:creature).permit(:name,:description)
		creature = Creature.new(creature_params)
		if creature.save 
			redirect_to creature_path(creature)
		end 
	end 

	def show 
		creature_id = params[:id]
		@creature = Creature.find_by_id(creature_id)
	end 

	def edit 
		creature_id = params[:id]
		@creature = Creature.find_by_id(creature_id)
	end 

	def update 
		creature_id = params[:id]
		@creature = Creature.find_by_id(creature_id)
		creature.update_attributes(creature_params)
		redirect_to creature_path(creature)
	end 

	def creature_params 
		params.require(:creature).permit(:name, :description)
	end 

	def destroy
    creature_id = params[:id]
    creature = Creature.find_by_id(creature_id)
    creature.destroy
    redirect_to creatures_path
 	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/edit.html.erb
<h1>Edit Creature Info</h1>

<%= form_for @creature do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.submit "Save Creature" %>
<% end %>

app/views/creatures/index.html.erb
<h1>Creatures</h1>
<nav>
	<%= link_to "Existing", creatures_path %>
	<%= link_to "New", new_creature_path %>
<br> 
<br> 
</nav>

<% @creatures.each do |creature| %>
  <p>Name: <%= creature.name %></p>
  <p>Description: <%= creature.description %></p>
  <br>
  <a href="/creatures/<%= creature.id %>">Show page</a> <!-- TODO: smelly -->
<% end %>

app/views/creatures/new.html.erb
<h1>Create a new Creature</h1>

<%= form_for :creature do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>  
  <%= f.submit "Save Creature", class: 'btn btn-primary' %>
<% end %>

app/views/creatures/show.html.erb
<br>
<p>Name: <%= @creature.name %></p>
<p>Description: <%= @creature.description %></p>
<%= button_to "Delete", :@creature, method: :delete %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BogAppOne</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    <%= yield %>
    </div>
  </body>
</html>